<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <RootNamespace>Ramazan_Vakti</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>ramadan.ico</ApplicationIcon>
    <AssemblyTitle>Ramazan Vakti</AssemblyTitle>
    <AssemblyProduct>Ramazan Vakti</AssemblyProduct>
    <Description>Ramazan Vakti</Description>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="SettingsForm.cs" />
    <Compile Remove="SettingsForm.Designer.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Remove="SettingsForm.resx" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="ramadan.ico" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>